### ISSUE TITLE
Boolean traits shows as fields, any input leads to mismatch of types sting!=boolean

### ISSUE THREAD

**Issue by DeamonMV** [dfoxg/kratos-admin-ui#168]
**Describe the bug**
Boolean traits shows as fields, any input leads to mismatch of types sting!=boolean, which lead to problem to update the traits.

**To Reproduce**
1. create a JSON schema 

```
{
  "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "definitions": {
    "tosUrl": {
      "type": "string",
      "const": "http://example.com/terms"
    }
  },
  "properties": {
    "traits": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "title": "E-Mail",
          "minLength": 3,
          "ory.sh/kratos": {
            "credentials": {
              "password": {
                "identifier": true
              }
            },
            "verification": {
              "via": "email"
            },
            "recovery": {
              "via": "email"
            }
          }
        },
        "username": {
          "title": "Username",
          "type": "string",
          "readOnly": true
        },
        "name": {
          "type": "object",
          "properties": {
            "first": {
              "title": "First Name",
              "type": "string"
            },
            "last": {
              "title": "Last Name",
              "type": "string"
            }
          }
        },
        "tos": {
          "title": "Accept Terms of Service",
          "type": "boolean",
          "description": "I accept the terms of service",
          "writeOnly": true,
          "tosUrl": {
            "$ref": "#/definitions/tosUrl"
           }
        },
        "newsletter": {
          "type": "boolean",
          "title": "Newsletter subscription"
        }
      },
      "required": [
        "email",
        "username",
        "tos"
      ],
      "additionalProperties": false
    }
  }
}
```

3. register and verify user
4. open kratos-admin-ui
5. open created user on edit
6. update any boolean traits - `Accept Terms of Service` or `Newsletter subscription`
7. See error
`{"code":400,"status":"Bad Request","reason":"I[#/traits/newsletter] S[#/properties/traits/properties/newsletter/type] expected boolean, but got string","message":"The request was malformed or contained invalid parameters"}`

**Expected behavior**
kratos-admin-ui shows checkbox as a checkbox, update of the checkbox passes without errors

**Screenshots**
![image](https://github.com/dfoxg/kratos-admin-ui/assets/12302678/23d859ee-da7b-444d-88cc-0764e8621094)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version `123.0.6312.123`

**Additional context**

kratos version 1.1.0

kratos-admin-ui used inside docker-compose.yaml as this 

```
  kratos-admin-ui:
    image: ghcr.io/dfoxg/kratos-admin-ui
    ports:
      - 8080:8080
    environment:
      - KRATOS_ADMIN_URL=http://kratos:4434
      - KRATOS_PUBLIC_URL=http://kratos:4433
    depends_on:
      - kratos
      - auth-db
    networks:
      - intranet
```

**Comment by dfoxg** [comment]
Thanks for reporting that, i'll have a look at it :)

**Comment by DeamonMV** [comment]
@dfoxg Thank you
Now it's work fine

![image](https://github.com/dfoxg/kratos-admin-ui/assets/12302678/d79fa0eb-4367-4449-8c90-a4299e92bba9)
