### ISSUE TITLE
Tag is listed incorrectly

### ISSUE THREAD

**Issue by SorsOps** [dfoxg/kratos-admin-ui#169]
**Describe the bug**
Attempted to pull `ghcr.io/dfoxg/kratos-admin-ui:v2.3.1` and received an error

**To Reproduce**
- docker pull ghcr.io/dfoxg/kratos-admin-ui:v2.3.1

**Expected behavior**
The image is retrieved

This is occuring because your tags have changed and `v2.3.1` was published as just `2.3.1` https://github.com/dfoxg/kratos-admin-ui/pkgs/container/kratos-admin-ui/201579567?tag=2.3.1

Please can you amend or update the docs

**Comment by dfoxg** [comment]
Thanks, I'm gonna fix that!

**Comment by dfoxg** [comment]
Fixed with [v2.3.2](https://github.com/dfoxg/kratos-admin-ui/pkgs/container/kratos-admin-ui/207543231?tag=v2.3.2). Thanks!
