### ISSUE TITLE
Getting CORS errors

### ISSUE THREAD

**Issue by zootopialover** [dfoxg/kratos-admin-ui#23]
Hey @dfoxg, thanks for sharing amazing work!

![image](https://user-images.githubusercontent.com/22075148/159965071-979d7efd-a488-4b4a-b686-dc3fe0d5ef3c.png)

I've deployed your repo [here](https://client.freshes.ca) after replacing URLs with our own `account.freshes.ca` but it's showing CORS errors.
FYI, we're using Ory Kratos cloud, not running a local instance of Kratos.

Do you have any idea why? We added `client.freshes.ca` in the allowed URLs as well in Ory account.

Looking forward to hearing back from you soon!

Thanks,

**Comment by dfoxg** [comment]
Hi @zootopialover,

thanks for using the software!
Your API isn´t sending any CORS-Headers:
![image](https://user-images.githubusercontent.com/28670365/159993155-68f044be-232b-4dea-a228-8b7c18b757fd.png)

Please check your config, maybe cloudflare removes the headers.
