### ISSUE TITLE
Promise is not resolved on browser reload - Edit Identity

### ISSUE THREAD

**Issue by anupriya17** [dfoxg/kratos-admin-ui#63]
**Describe the bug**
When browser is reloaded the edit identity is not working due to the schema promise is not resolved.
https://github.com/dfoxg/kratos-admin-ui/blob/0977adc5c331b4240c55d2c0e0ac1d7c3e90f420/kratos-admin-ui/src/service/schema-service.ts#L39-L44

But the edit.tsx expects the schema which is not resolved sometimes and schema is undefined - may be network issue
https://github.com/dfoxg/kratos-admin-ui/blob/0977adc5c331b4240c55d2c0e0ac1d7c3e90f420/kratos-admin-ui/src/sites/identities/edit/edit.tsx#L40-L42

**To Reproduce**
1. Select Identity and click edit
2. Reload the page 
3. See error

```
schema-service.ts:50 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'properties')
    at SchemaService.getSchemaFields (schema-service.ts:50:1)
    at EditIdentitySite.mapEntity (edit.tsx:42:1)
```

**Comment by dfoxg** [comment]
Thanks @anupriya17, I will look at it :)
