### ISSUE TITLE
Preserve Metadata during edit

### ISSUE THREAD

**Issue by anupriya17** [dfoxg/kratos-admin-ui#64]
Edit removes the existing metadata_public and metadata_admin. I think adding these will preserve the values

https://github.com/dfoxg/kratos-admin-ui/blob/0977adc5c331b4240c55d2c0e0ac1d7c3e90f420/kratos-admin-ui/src/sites/identities/edit/edit.tsx#L95-L98

```
 metadata_public: this.state.identity?.metadata_public,
 metadata_admin: this.state.identity?.metadata_admin
```

**Comment by dfoxg** [comment]
fixed with https://github.com/dfoxg/kratos-admin-ui/pull/65
